api-module: orchestration
base:
  application:
    name: isc-capc-service
    version: 1.0.0
  swagger:
    enable: true
  endpoint:
    health:
      enable: true
  server:
    enable: true
    port: 38300
  datasource:
    host: 10.30.30.95
    port: 23306
    driverName: mysql
    username: isyscore
    password: Isysc0re
    database: isc_ecology_orchestration
    debug: true
feign:
  permission: http://10.30.30.95:32100